#!/usr/bin/python

'''Gitian package builder'''

import sys
import os
import git
from gitian_util import *
from optparse import OptionParser
#from gettext import gettext as _

if __name__ == "__main__":
    parser = OptionParser()
    parser.prog = "gitian package-build"
    optparser_extend(parser)
    parser.add_option ("-c", "--clean", default=False, action="store_true",
                       dest="clean",
                       help="Start from a pristine checkout")
    parser.add_option ("-n", "--dry-run", default=False, action="store_true",
                       dest="dryrun",
                       help="Do not actually build - useful when cleaning")
    parser.add_option ("-b", "--blankslate", default=False, action="store_true",
                       dest="blankslate",
                       help="Clean out all installed gems before attempting build")
    parser.add_option ("-d", "--dest",
                       dest="dest",
                       help="Destination directory (default ROOT/dist)")
    parser.usage = """gitian package-new [-c COMMIT] REPOS-URL [NAME]
or:
    gitian package-new GITHUB-COMMIT-URL [NAME]
  Creates a package within a Gitian repository
"""
    (options, args) = parser.parse_args()
    if not args:
        parser.error("must supply package name")
        sys.exit(1)

    repos = repository_root()

    if options.dest:
        destination = os.path.abspath(options.dest)
    else:
        destination = os.path.join(repos, "dist")

    name = args[0]
    (package_dir, control, ptr) = open_package(name)

    if options.dryrun:
        sys.exit(0)

    if control['packager'] == 'rubygems':
        if options.blankslate:
            rubygems_dir = os.path.join(destination, '.gem')
            if os.access(rubygems_dir, os.F_OK):
                shutil.rmtree(rubygems_dir)
        ensure_rubygems_installed(destination)
        ensure_gem_installed('rake', destination)
        do_copy = True
        build_gem(package_dir, control, ptr, destination, do_copy, options.clean)
    elif control['packager'] == 'tar':
        do_copy = True
        build_tar(package_dir, control, ptr, destination, do_copy, options.clean)
    else:
        print >> sys.stderr, "unknown packager %s" % (control['packager'])
        
