#!/usr/bin/python

'''Gitian package builder'''

import sys
import os
import git
from gitian_util import *
from optparse import OptionParser
#from gettext import gettext as _

if __name__ == "__main__":
    parser = OptionParser()
    parser.prog = "gitian package-build"
    optparser_extend(parser)
    parser.add_option ("-c", "--clean", default=False, action="store_true",
                       dest="clean",
                       help="Start from a pristine checkout")
    parser.add_option ("-d", "--dest",
                       dest="dest",
                       help="Destination directory (default ROOT/dist)")
    parser.usage = """gitian package-new [-c COMMIT] REPOS-URL [NAME]
or:
    gitian package-new GITHUB-COMMIT-URL [NAME]
  Creates a package within a Gitian repository
"""
    (options, args) = parser.parse_args()
    if not args:
        parser.error("must supply package name")
        exit(1)

    repos = repository_root()

    if options.dest:
        destination = os.path.abspath(options.dest)
    else:
        destination = os.path.join(repos, "dist")

    name = args[0]
    (package_dir, control, ptr) = open_package(name)

    if control['packager'] == 'rubygems':
        ensure_rubygems_installed(destination)
        ensure_gem_installed('rake', destination)
        build_gem(package_dir, control, ptr, destination, True, options.clean)
    else:
        print >> sys.stderr, "unknown packager %s" % (control['packager'])
        
