#!/usr/bin/python

'''Gitian package creator'''

import os
import sys
from gitian_util import *
from optparse import OptionParser

USAGE = """Usage: gitian package-new NAME REPOS-URL REPOS-COMMIT
  Creates a new package within a Gitian repository
"""
if __name__ == "__main__":
  parser = OptionParser()
  parser.prog = "gitian package-build"
  optparser_extend(parser)
  (options, args) = parser.parse_args()

  if len(args) != 3:
    print >> sys.stderr, USAGE
    exit(1)

  name = args[0]
  url = args[1]
  commit = args[2]

  if os.access(name, os.F_OK):
    print >> sys.stderr, "already exists"
    exit(1)

  os.makedirs(name)
  f = open(os.path.join(name, name + ".gdsc"), "w")
  f.write("""--- 
name: "%s"
packager: rubygems
packager_options:
  rake_cmd: "rake gem"
""" % (name))
  f.close()

  f = open(os.path.join(name, name + ".vcptr"), "w")
  f.write("""---
url: "%s"
commit: %s
""" % (url, commit))
  f.close()

  print "created %s" %(name)
