require 'rubygems'
require 'rake'
require 'rake/rdoctask'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.rubyforge_project = "gitian-tools"
    gem.name = "gitian"
    gem.summary = "Use a Gitian repository as the rubygems source"
    gem.description = "Add the 'gitian' sub-commands to the gem command"
    gem.email = "info.deb@nginz.org"
    gem.homepage = "http://gitian.org/"
    gem.authors = ["Miron Cuperman"]
    gem.files = FileList["lib/rubygems_plugin.rb", "lib/commands/*"]
    gem.test_files = FileList["spec/*.rb", "spec/commands/*"]
    gem.executables = []
    gem.add_development_dependency "rspec", ">= 1.2.0"
    gem.required_rubygems_version = Gem::Requirement.new(">= 1.3.5") if gem.respond_to? :required_rubygems_version=
    gem.post_install_message = <<MESSAGE

========================================================================

           Thanks for installing Gitian! You can now run:

    gem gitian        use Gitian.org or another distribution as your main gem source

========================================================================

MESSAGE
  end
rescue LoadError
  puts "Jeweler is not available. Install it with: gem install jeweler"
end

begin
  Jeweler::RubyforgeTasks.new
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "a dependency of Jeweler is not available. Install them with: gem install rubyforge gemcutter"
end

require 'spec/rake/spectask'
Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
end

task :gem => :build

task :default => :spec

task :spec => :check_dependencies

desc "release with no version change"
task :dist => [:clean, :release]

namespace :dist do
  desc "release patch"
  task :patch => [:clean, "version:bump:patch", :release]
  desc "release with minor version bump"
  task :minor => [:clean, "version:bump:minor", :release]
end

Rake::RDocTask.new do |rd|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rd.main = "README.rdoc"
  rd.rdoc_dir = "rdoc"
  rd.title = "Gitian Gem #{version}"
  rd.rdoc_files.include("README.rdoc", "lib/**/*.rb")
end

task :clean do
end
